#!/bin/sh
#tmpfile="$1-new"
#outfile="$1"
tmpfile="/tmp/$$"
outfile="timestamp.h"

echo "outputting to $outfile"

echo "// generated by $0" > "$tmpfile"
echo "#define BUILD_TIMESTAMP \"$(date +%Y%m%d_%H%M%S)\"" >> "$tmpfile"
if diff "$tmpfile" "$outfile" 2>/dev/null || ! [ -f "$outfile" ]; then
  mv -f -- "$tmpfile" "$outfile"
else
  rm -f -- "$tmpfile"
fi
