
/* generated by codex to test pitch tracker.
 * compile with:
 * c++ -std=c++17 -O2 -DMETER_DATA_ONLY -Isrc pitchtracker_test.cpp tuner.cpp -o /tmp/
 */

#include "tuner.h"

#include <cmath>
#include <cstdio>
#include <vector>

static float wave (double phase, int which) {
  switch (which) {
    case 1: return phase < 0.5 ? 1.0f : -1.0f;
    case 2: return (float) (phase * 2.0 - 1.0);
    case 3: return (float) (1.0 - phase * 2.0);
    case 4: return (float) (1.0 - 4.0 * std::abs (phase - 0.5));
    default: return (float) std::sin (2.0 * M_PI * phase);
  }
}

int main () {
  constexpr int sr = 48000;
  for (float freq : { 36.0f, 40.0f, 110.0f, 440.0f }) {
    for (int waveform = 0; waveform < 5; ++waveform) {
      c_pitchtracker tracker;
      tracker.set_samplerate (sr);
      std::vector<float> block (256);
      double phase = 0.0;
      for (int n = 0; n < 24; ++n) {
        for (float &sample : block) {
          sample = wave (phase, waveform) * 0.5f;
          phase += freq / sr;
          phase -= std::floor (phase);
        }
        tracker.process_block (block.data (), (int) block.size ());
      }
      tracker.analyze ();
      std::printf ("%7.1f waveform %d -> %9.3f\n",
                   freq, waveform, tracker.detected_freq.load ());
    }
  }
}
